import { writeFileSync } from "fs";
import { join } from "path";

/**
 * Setup Frontend Environment
 * This script helps configure the frontend after contract deployment
 *
 * Usage:
 * 1. Deploy contracts: npx hardhat run scripts/deploy.ts --network localhost
 * 2. Copy the contract address from the deployment output
 * 3. Run: npx ts-node scripts/setup-frontend.ts <CONTRACT_ADDRESS>
 */

const contractAddress = process.argv[2];

if (!contractAddress || !contractAddress.startsWith("0x")) {
  console.error("❌ Error: Please provide a valid contract address");
  console.error("Usage: npx ts-node scripts/setup-frontend.ts <CONTRACT_ADDRESS>");
  console.error("\nExample: npx ts-node scripts/setup-frontend.ts 0x5FbDB2315678afecb367f032d93F642f64180aa3");
  process.exit(1);
}

// Determine network from hardhat network
const network = process.env.HARDHAT_NETWORK || "localhost";
let chainId = "31337";
let networkName = "Hardhat Local";

if (network === "polygonMumbai") {
  chainId = "80001";
  networkName = "Polygon Mumbai";
} else if (network === "polygonAmoy") {
  chainId = "80002";
  networkName = "Polygon Amoy";
}

const envContent = `# Arras Labs Real Estate Tokenization - Frontend Configuration
# Auto-generated by setup-frontend.ts

# Contract address
VITE_CONTRACT_ADDRESS=${contractAddress}

# Network Configuration
VITE_CHAIN_ID=${chainId}
VITE_NETWORK_NAME=${networkName}
`;

const frontendEnvPath = join(__dirname, "../frontend/.env");

try {
  writeFileSync(frontendEnvPath, envContent);
  console.log("✅ Frontend .env file created successfully!");
  console.log("\n📋 Configuration:");
  console.log(`   Contract Address: ${contractAddress}`);
  console.log(`   Chain ID: ${chainId}`);
  console.log(`   Network: ${networkName}`);
  console.log("\n🚀 Next steps:");
  console.log("   1. cd frontend");
  console.log("   2. npm install");
  console.log("   3. npm run dev");
  console.log("\n🌐 Frontend will be available at http://localhost:5173");
} catch (error) {
  console.error("❌ Error writing .env file:", error);
  process.exit(1);
}
